spring:
  application:
    name: ms-transactions
  data:
    mongodb:
      uri: "mongodb+srv://mean_user:EWpWinEnfJ2nc32R@cluster0.hcqaq.mongodb.net/proyecto1db?authSource=admin&replicaSet=atlas-m2z4np-shard-0&readPreference=primary&ssl=true"

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
